#!/usr/bin/env bash
#
# extract-current-kernel-config.sh - Extract the running kernel's .config
# from /boot/config-$(uname -r) or /proc/config.gz and store it as an
# internal artefact under rhel-kernel/rhelX/original/ together with a YAML
# manifest describing its provenance.
#
# This is the ONLY supported way to populate the original/ directories.
# Do not hand-author kernel configs.
#
# Usage:
#   extract-current-kernel-config.sh [--help] [--verbose]
#                                    [--dest-dir DIR] [--rhel-major N]
#
# Exit codes:
#   0  config extracted and manifest written
#   1  no usable config source found / error
#
set -euo pipefail

__find_lib() {
  local d
  d=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
  while [ "$d" != "/" ]; do
    [ -r "$d/scripts/lib/common.sh" ] && { echo "$d/scripts/lib/common.sh"; return 0; }
    d=$(dirname "$d")
  done
  return 1
}
LIB=$(__find_lib) || { echo "ERROR: cannot locate scripts/lib/common.sh" >&2; exit 1; }
REPO_ROOT=$(cd "$(dirname "$LIB")/../.." && pwd)
# shellcheck source=/dev/null
. "$LIB"

DEST_DIR=""
RHEL_MAJOR=""

usage() {
  cat <<'EOF'
extract-current-kernel-config.sh - extract the running kernel .config.

Usage:
  extract-current-kernel-config.sh [options]

Options:
  --help, -h        Show this help and exit.
  --verbose, -v     Enable debug logging.
  --rhel-major N    Override the detected RHEL major version (4..10).
  --dest-dir DIR    Override the destination directory. Default:
                    <repo>/rhel-kernel/rhel<major>/original

Sources tried (in order):
  1. /boot/config-$(uname -r)
  2. /proc/config.gz (gunzipped)

Outputs:
  <dest>/config-<kernel-version>.config
  <dest>/config-<kernel-version>.manifest.yml
EOF
}

main() {
  while [ "$#" -gt 0 ]; do
    case "$1" in
      -h|--help) usage; exit 0 ;;
      -v|--verbose) VERBOSE=1; export VERBOSE ;;
      --dest-dir) DEST_DIR="${2:?--dest-dir needs a value}"; shift ;;
      --rhel-major) RHEL_MAJOR="${2:?--rhel-major needs a value}"; shift ;;
      *) log_warn "Ignoring unknown argument: $1" ;;
    esac
    shift
  done

  detect_os
  [ -n "$RHEL_MAJOR" ] || RHEL_MAJOR="$OS_VERSION_MAJOR"
  if [ "$RHEL_MAJOR" = "unknown" ]; then
    die "Could not determine RHEL major version; pass --rhel-major N."
  fi

  if [ -z "$DEST_DIR" ]; then
    DEST_DIR="$REPO_ROOT/rhel-kernel/rhel${RHEL_MAJOR}/original"
  fi
  mkdir -p "$DEST_DIR"

  local kver src dest_cfg
  kver=$(uname -r)
  dest_cfg="$DEST_DIR/config-${kver}.config"

  if [ -r "/boot/config-${kver}" ]; then
    src="/boot/config-${kver}"
    cp "/boot/config-${kver}" "$dest_cfg"
    log_ok "Copied /boot/config-${kver} -> $dest_cfg"
  elif [ -r /proc/config.gz ]; then
    src="/proc/config.gz"
    require_command gunzip
    gunzip -c /proc/config.gz >"$dest_cfg"
    log_ok "Extracted /proc/config.gz -> $dest_cfg"
  else
    die "No kernel config source found (/boot/config-${kver} or /proc/config.gz)."
  fi

  # Provenance manifest.
  local manifest sum
  manifest="$DEST_DIR/config-${kver}.manifest.yml"
  if has_command sha256sum; then
    sum=$(sha256sum "$dest_cfg" | awk '{print $1}')
  elif has_command md5sum; then
    sum="md5:$(md5sum "$dest_cfg" | awk '{print $1}')"
  else
    sum="unavailable"
  fi
  {
    echo "# Provenance manifest for an extracted kernel config."
    echo "# Generated by extract-current-kernel-config.sh - do not edit by hand."
    echo "hostname: $(hostname -s 2>/dev/null || hostname 2>/dev/null || echo host)"
    echo "date: $(date +%Y-%m-%dT%H:%M:%S%z)"
    echo "os: \"${OS_NAME}\""
    echo "os_id: ${OS_ID}"
    echo "rhel_major: ${RHEL_MAJOR}"
    echo "kernel: ${kver}"
    echo "architecture: ${OS_ARCH}"
    echo "source: ${src}"
    echo "config_file: $(basename "$dest_cfg")"
    echo "sha256: ${sum}"
  } >"$manifest"

  log_ok "Wrote manifest: $manifest"
  log_info "Remember to commit this artefact if it is legitimately collected."
}

main "$@"
